#checks:
#    php:
#        code_rating: true
#        duplication: true
#
build:
    environment:
        php:
            version: 8.4.0
#tools:
#    external_code_coverage: true
#
filter:
    excluded_paths:
        - vendor/*
