checks:
    php:
        code_rating: true
        duplication: true
        
build:
    environment:
        php:
            version: [5.5, 5.6, 7.0, 7.1, 7.2]

filter:
    excluded_paths:
        - bin/*
        - examples/*
        - tests/*
        - vendor/*
