checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 7.2
tools:
    external_code_coverage: true

filter:
    excluded_paths:
        - bin/*
        - examples/*
        - tests/*
        - vendor/*
