checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 7.2
    tests:
        override:
            -
                command: 'bin/phpunit --coverage-clover=scrutinizer'
                coverage:
                    file: 'scrutinizer'
                    format: 'clover'
filter:
    excluded_paths:
        - bin/*
        - examples/*
        - tests/*
        - vendor/*
