checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 7.2

filter:
    excluded_paths:
        - bin/*
        - examples/*
        - tests/*
        - vendor/*
